### ISSUE TITLE
es TODO for R version 4.3.0

### ISSUE THREAD

**Issue by hturner** [r-devel/translations-campfire#18]
- [ ] `4.3.0/base/po/R-base.pot`
- [ ] `4.3.0/base/po/R.pot`
- [ ] `4.3.0/base/po/RGui.pot`
- [ ] `4.3.0/compiler/po/R-compiler.pot`
- [ ] `4.3.0/graphics/po/graphics.pot`
- [ ] `4.3.0/graphics/po/R-graphics.pot`
- [ ] `4.3.0/grDevices/po/grDevices.pot`
- [ ] `4.3.0/grDevices/po/R-grDevices.pot`
- [ ] `4.3.0/grid/po/grid.pot`
- [ ] `4.3.0/grid/po/R-grid.pot`
- [ ] `4.3.0/methods/po/methods.pot`
- [ ] `4.3.0/methods/po/R-methods.pot`
- [ ] `4.3.0/parallel/po/parallel.pot`
- [ ] `4.3.0/parallel/po/R-parallel.pot`
- [ ] `4.3.0/splines/po/R-splines.pot`
- [ ] `4.3.0/splines/po/splines.pot`
- [ ] `4.3.0/stats/po/R-stats.pot`
- [ ] `4.3.0/stats/po/stats.pot`
- [ ] `4.3.0/stats4/po/R-stats4.pot`
- [ ] `4.3.0/tcltk/po/R-tcltk.pot`
- [ ] `4.3.0/tcltk/po/tcltk.pot`
- [ ] `4.3.0/tools/po/R-tools.pot`
- [ ] `4.3.0/tools/po/tools.pot`
- [ ] `4.3.0/utils/po/R-utils.pot`
- [ ] `4.3.0/utils/po/utils.pot`
- [ ] `Recommended/boot/po/R-boot.pot`
- [ ] `Recommended/class/po/R-class.pot`
- [ ] `Recommended/cluster/po/cluster.pot`
- [ ] `Recommended/cluster/po/R-cluster.pot`
- [ ] `Recommended/foreign/po/foreign.pot`
- [ ] `Recommended/foreign/po/R-foreign.pot`
- [ ] `Recommended/KernSmooth/po/R-KernSmooth.pot`
- [ ] `Recommended/lattice/po/R-lattice.pot`
- [ ] `Recommended/MASS/po/R-MASS.pot`
- [ ] `Recommended/Matrix/po/Matrix.pot`
- [ ] `Recommended/Matrix/po/R-Matrix.pot`
- [ ] `Recommended/mgcv/po/mgcv.pot`
- [ ] `Recommended/mgcv/po/R-mgcv.pot`
- [ ] `Recommended/nlme/po/nlme.pot`
- [ ] `Recommended/nlme/po/R-nlme.pot`
- [ ] `Recommended/nnet/po/R-nnet.pot`
- [ ] `Recommended/rpart/po/R-rpart.pot`
- [ ] `Recommended/rpart/po/rpart.pot`
- [ ] `Recommended/spatial/po/R-spatial.pot`

**Comment by llrs** [comment]
@hturner the file I was editing was this one https://github.com/r-devel/translations-campfire/blob/main/4.3.0/base/po/RGui-es.po but surprisingly here all characters are correctly shown. So the problem is on my side.

**Comment by hturner** [comment]
I have a similar problem when I try to open the file in RStudio. It looks okay for me if I open it in poedit or notepad (on Windows). The metadata says the encoding is ISO-8859-1. I tried using File > Reopen with Encoding ... > ISO-8859-1 in RStudio but that didn't work (the file looked blank). Does it work for you?

Otherwise we could consider converting to UTF-8, it is preferred in any case.

**Comment by llrs** [comment]
Maybe the problem is that I had regenerated all those files (as I had run the po_dir_setup on my own svn local repository).

After reverting the changes and pulling from the repo again, poedit opens it correctly and RStudio after doing the "reopening with encoding" ...  shows  correctly the file (RStudio 2022.02.2+485 "Prairie Trillium" Release (8acbd38b0d4ca3c86c570cf4112a8180c48cc6fb, 2022-04-19) for Ubuntu Bionic).

I don't know if there are problems for other languages but from my understanding is that UTF-8 is the most complete encoding and it is gaining support from R itself so maybe it is worth to encode translations in UTF.8 too.
